-- Add DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) to all timestamp columns
-- that were previously NOT NULL with no default, causing NULL values on initial INSERT.

ALTER TABLE `upsell_rules`
  MODIFY COLUMN `updatedAt` DATETIME(3) NOT NULL
  DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);

ALTER TABLE `cart_drawer`
  MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL
  DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);

ALTER TABLE `fbt_widget`
  MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL
  DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);

ALTER TABLE `coupon_slider_widget`
  MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL
  DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);

ALTER TABLE `coupons`
  MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL
  DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);

ALTER TABLE `shops`
  MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL
  DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);
