-- Combo Forge module: create all 12 required tables in cart_drawer_ninja.
-- Drops the two orphaned Prisma-managed tables (combotemplate, comboanalytic)
-- that were never queried by any actual route.
--
-- Schemas are intentionally normalised: every styling property is its own
-- column so that UI customisation data can be queried/filtered individually
-- rather than deserialized from a JSON blob.

-- ── core ──────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS `combo_templates` (
  `id`                 INT           NOT NULL AUTO_INCREMENT,
  `shop_domain`        VARCHAR(255)  NOT NULL,
  `name`               VARCHAR(255)  NOT NULL DEFAULT '',
  `slug`               VARCHAR(255)  NULL,
  `template_type`      ENUM('grid','carousel','premium') NOT NULL DEFAULT 'grid',
  `status`             ENUM('draft','published','archived') NOT NULL DEFAULT 'draft',
  `is_active`          TINYINT(1)    NOT NULL DEFAULT 1,
  `version`            INT           NOT NULL DEFAULT 1,
  `thumbnail_url`      VARCHAR(500)  NULL,
  `description`        TEXT          NULL,
  `features`           JSON          NULL,
  `customization_data` LONGTEXT      NULL,
  `page_handle`        VARCHAR(255)  NULL,
  `page_id`            VARCHAR(255)  NULL,
  `page_url`           VARCHAR(500)  NULL,
  `bg_color`           VARCHAR(20)   NOT NULL DEFAULT '#ffffff',
  `text_color`         VARCHAR(20)   NOT NULL DEFAULT '#202223',
  `accent_color`       VARCHAR(20)   NOT NULL DEFAULT '#008060',
  `border_radius`      VARCHAR(20)   NOT NULL DEFAULT '8px',
  `font_family`        VARCHAR(100)  NOT NULL DEFAULT 'Inter',
  `created_by`         VARCHAR(255)  NULL,
  `created_at`         DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`         DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_shop`   (`shop_domain`),
  INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `combo_analytics` (
  `id`          INT           NOT NULL AUTO_INCREMENT,
  `shop_domain` VARCHAR(255)  NOT NULL,
  `template_id` INT           NULL,
  `event_type`  VARCHAR(50)   NOT NULL,
  `revenue`     DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `session_id`  VARCHAR(100)  NULL,
  `referrer`    VARCHAR(500)  NULL,
  `user_agent`  VARCHAR(500)  NULL,
  `recorded_at` DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_shop`        (`shop_domain`),
  INDEX `idx_template`    (`template_id`),
  INDEX `idx_event`       (`event_type`),
  INDEX `idx_recorded_at` (`recorded_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── sub-tables (all cascade-delete from combo_templates) ──────────────────────

CREATE TABLE IF NOT EXISTS `template_pages` (
  `id`              INT          NOT NULL AUTO_INCREMENT,
  `template_id`     INT          NOT NULL,
  `shop_domain`     VARCHAR(255) NOT NULL,
  `page_id`         VARCHAR(100) NULL,
  `page_handle`     VARCHAR(255) NULL,
  `page_title`      VARCHAR(255) NULL,
  `preview_url`     VARCHAR(500) NULL,
  `published_url`   VARCHAR(500) NULL,
  `admin_url`       VARCHAR(500) NULL,
  `is_published`    TINYINT(1)   NOT NULL DEFAULT 0,
  `published_at`    DATETIME     NULL,
  `seo_title`       VARCHAR(255) NULL,
  `seo_description` TEXT         NULL,
  `created_at`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_template` (`template_id`),
  INDEX `idx_shop` (`shop_domain`),
  CONSTRAINT `fk_tp_template` FOREIGN KEY (`template_id`) REFERENCES `combo_templates` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `template_collections` (
  `id`                 INT          NOT NULL AUTO_INCREMENT,
  `template_id`        INT          NOT NULL,
  `shop_domain`        VARCHAR(255) NOT NULL,
  `collection_id`      VARCHAR(100) NOT NULL,
  `collection_title`   VARCHAR(255) NULL,
  `handle`             VARCHAR(255) NULL,
  `products_per_row`   INT          NOT NULL DEFAULT 3,
  `max_products`       INT          NOT NULL DEFAULT 12,
  `display_mode`       ENUM('grid','carousel') NOT NULL DEFAULT 'grid',
  `slider_speed`       INT          NOT NULL DEFAULT 3000,
  `infinite_loop`      TINYINT(1)   NOT NULL DEFAULT 0,
  `autoplay`           TINYINT(1)   NOT NULL DEFAULT 1,
  `show_arrows`        TINYINT(1)   NOT NULL DEFAULT 1,
  `show_dots`          TINYINT(1)   NOT NULL DEFAULT 1,
  `sort_order`         VARCHAR(50)  NOT NULL DEFAULT 'manual',
  `bg_color`           VARCHAR(20)  NOT NULL DEFAULT '#ffffff',
  `card_bg_color`      VARCHAR(20)  NOT NULL DEFAULT '#ffffff',
  `card_border_color`  VARCHAR(20)  NOT NULL DEFAULT '#e1e3e5',
  `card_border_width`  VARCHAR(10)  NOT NULL DEFAULT '1px',
  `card_border_radius` VARCHAR(20)  NOT NULL DEFAULT '8px',
  `card_shadow`        TINYINT(1)   NOT NULL DEFAULT 0,
  `title_color`        VARCHAR(20)  NOT NULL DEFAULT '#202223',
  `title_font_size`    VARCHAR(10)  NOT NULL DEFAULT '14px',
  `title_font_weight`  VARCHAR(10)  NOT NULL DEFAULT '600',
  `price_color`        VARCHAR(20)  NOT NULL DEFAULT '#008060',
  `price_font_size`    VARCHAR(10)  NOT NULL DEFAULT '14px',
  `btn_text`           VARCHAR(100) NOT NULL DEFAULT 'Add to Cart',
  `btn_bg_color`       VARCHAR(20)  NOT NULL DEFAULT '#008060',
  `btn_text_color`     VARCHAR(20)  NOT NULL DEFAULT '#ffffff',
  `btn_border_radius`  VARCHAR(20)  NOT NULL DEFAULT '6px',
  `btn_hover_color`    VARCHAR(20)  NOT NULL DEFAULT '#006e52',
  `hover_effect`       VARCHAR(50)  NOT NULL DEFAULT 'none',
  `padding`            VARCHAR(20)  NOT NULL DEFAULT '16px',
  `gap`                VARCHAR(20)  NOT NULL DEFAULT '16px',
  `created_at`         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_template` (`template_id`),
  CONSTRAINT `fk_tc_template` FOREIGN KEY (`template_id`) REFERENCES `combo_templates` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `template_banners` (
  `id`                      INT          NOT NULL AUTO_INCREMENT,
  `template_id`             INT          NOT NULL,
  `shop_domain`             VARCHAR(255) NOT NULL,
  `desktop_image`           VARCHAR(500) NULL,
  `desktop_height`          VARCHAR(20)  NOT NULL DEFAULT '400px',
  `desktop_width`           VARCHAR(20)  NOT NULL DEFAULT '100%',
  `desktop_border_radius`   VARCHAR(20)  NOT NULL DEFAULT '12px',
  `desktop_overlay_color`   VARCHAR(50)  NOT NULL DEFAULT 'rgba(0,0,0,0.3)',
  `desktop_overlay_opacity` DECIMAL(3,2) NOT NULL DEFAULT 0.30,
  `mobile_image`            VARCHAR(500) NULL,
  `mobile_height`           VARCHAR(20)  NOT NULL DEFAULT '250px',
  `mobile_width`            VARCHAR(20)  NOT NULL DEFAULT '100%',
  `mobile_border_radius`    VARCHAR(20)  NOT NULL DEFAULT '8px',
  `mobile_overlay_color`    VARCHAR(50)  NOT NULL DEFAULT 'rgba(0,0,0,0.3)',
  `mobile_overlay_opacity`  DECIMAL(3,2) NOT NULL DEFAULT 0.30,
  `title_text`              VARCHAR(255) NULL,
  `title_color`             VARCHAR(20)  NOT NULL DEFAULT '#ffffff',
  `title_font_size`         VARCHAR(10)  NOT NULL DEFAULT '32px',
  `title_font_weight`       VARCHAR(10)  NOT NULL DEFAULT '700',
  `title_alignment`         ENUM('left','center','right') NOT NULL DEFAULT 'center',
  `subtitle_text`           VARCHAR(255) NULL,
  `subtitle_color`          VARCHAR(20)  NOT NULL DEFAULT '#ffffff',
  `subtitle_font_size`      VARCHAR(10)  NOT NULL DEFAULT '18px',
  `cta_text`                VARCHAR(100) NULL,
  `cta_link`                VARCHAR(500) NULL,
  `cta_bg_color`            VARCHAR(20)  NOT NULL DEFAULT '#008060',
  `cta_text_color`          VARCHAR(20)  NOT NULL DEFAULT '#ffffff',
  `cta_border_radius`       VARCHAR(20)  NOT NULL DEFAULT '6px',
  `text_position`           ENUM('top','center','bottom') NOT NULL DEFAULT 'center',
  `text_padding`            VARCHAR(20)  NOT NULL DEFAULT '20px',
  `created_at`              DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`              DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_template` (`template_id`),
  INDEX `idx_shop` (`shop_domain`),
  CONSTRAINT `fk_tb_template` FOREIGN KEY (`template_id`) REFERENCES `combo_templates` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `template_settings` (
  `id`                     INT          NOT NULL AUTO_INCREMENT,
  `template_id`            INT          NOT NULL,
  `shop_domain`            VARCHAR(255) NOT NULL,
  `main_title`             VARCHAR(255) NULL,
  `main_title_color`       VARCHAR(20)  NOT NULL DEFAULT '#202223',
  `main_title_font_size`   VARCHAR(10)  NOT NULL DEFAULT '28px',
  `main_title_font_weight` VARCHAR(10)  NOT NULL DEFAULT '700',
  `subtitle`               VARCHAR(255) NULL,
  `subtitle_color`         VARCHAR(20)  NOT NULL DEFAULT '#6d7175',
  `subtitle_font_size`     VARCHAR(10)  NOT NULL DEFAULT '18px',
  `description`            TEXT         NULL,
  `description_color`      VARCHAR(20)  NOT NULL DEFAULT '#6d7175',
  `description_font_size`  VARCHAR(10)  NOT NULL DEFAULT '14px',
  `text_alignment`         ENUM('left','center','right') NOT NULL DEFAULT 'center',
  `cta_text`               VARCHAR(100) NOT NULL DEFAULT 'Shop Now',
  `cta_link`               VARCHAR(500) NULL,
  `cta_bg_color`           VARCHAR(20)  NOT NULL DEFAULT '#008060',
  `cta_text_color`         VARCHAR(20)  NOT NULL DEFAULT '#ffffff',
  `cta_border_radius`      VARCHAR(20)  NOT NULL DEFAULT '6px',
  `cta_hover_color`        VARCHAR(20)  NOT NULL DEFAULT '#006e52',
  `bg_color`               VARCHAR(20)  NOT NULL DEFAULT '#ffffff',
  `content_width`          VARCHAR(20)  NOT NULL DEFAULT '1200px',
  `section_gap`            VARCHAR(20)  NOT NULL DEFAULT '40px',
  `padding_top`            VARCHAR(20)  NOT NULL DEFAULT '60px',
  `padding_bottom`         VARCHAR(20)  NOT NULL DEFAULT '60px',
  `padding_left`           VARCHAR(20)  NOT NULL DEFAULT '20px',
  `padding_right`          VARCHAR(20)  NOT NULL DEFAULT '20px',
  `created_at`             DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`             DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_template` (`template_id`),
  INDEX `idx_shop` (`shop_domain`),
  CONSTRAINT `fk_ts_template` FOREIGN KEY (`template_id`) REFERENCES `combo_templates` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `template_typography` (
  `id`              INT          NOT NULL AUTO_INCREMENT,
  `template_id`     INT          NOT NULL,
  `shop_domain`     VARCHAR(255) NOT NULL,
  `section_key`     VARCHAR(50)  NOT NULL,
  `font_family`     VARCHAR(100) NOT NULL DEFAULT 'Inter',
  `font_size`       VARCHAR(10)  NOT NULL DEFAULT '16px',
  `font_weight`     VARCHAR(10)  NOT NULL DEFAULT '400',
  `font_color`      VARCHAR(20)  NOT NULL DEFAULT '#202223',
  `font_style`      VARCHAR(20)  NOT NULL DEFAULT 'normal',
  `alignment`       ENUM('left','center','right') NOT NULL DEFAULT 'left',
  `line_height`     VARCHAR(10)  NOT NULL DEFAULT '1.5',
  `letter_spacing`  VARCHAR(10)  NOT NULL DEFAULT 'normal',
  `text_transform`  VARCHAR(20)  NOT NULL DEFAULT 'none',
  `text_decoration` VARCHAR(20)  NOT NULL DEFAULT 'none',
  `created_at`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_template_section` (`template_id`, `section_key`),
  CONSTRAINT `fk_tty_template` FOREIGN KEY (`template_id`) REFERENCES `combo_templates` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `template_progressbars` (
  `id`                    INT          NOT NULL AUTO_INCREMENT,
  `template_id`           INT          NOT NULL,
  `shop_domain`           VARCHAR(255) NOT NULL,
  `is_enabled`            TINYINT(1)   NOT NULL DEFAULT 0,
  `bar_color`             VARCHAR(20)  NOT NULL DEFAULT '#e1e3e5',
  `filled_color`          VARCHAR(20)  NOT NULL DEFAULT '#008060',
  `text_color`            VARCHAR(20)  NOT NULL DEFAULT '#202223',
  `milestone_color`       VARCHAR(20)  NOT NULL DEFAULT '#008060',
  `success_color`         VARCHAR(20)  NOT NULL DEFAULT '#2e7d32',
  `background_color`      VARCHAR(20)  NOT NULL DEFAULT '#f6f6f7',
  `border_radius`         VARCHAR(20)  NOT NULL DEFAULT '8px',
  `height`                VARCHAR(20)  NOT NULL DEFAULT '8px',
  `label_text`            VARCHAR(255) NULL,
  `show_percentage`       TINYINT(1)   NOT NULL DEFAULT 0,
  `show_milestone_labels` TINYINT(1)   NOT NULL DEFAULT 1,
  `animation_enabled`     TINYINT(1)   NOT NULL DEFAULT 1,
  `animation_type`        VARCHAR(50)  NOT NULL DEFAULT 'ease',
  `milestone_shape`       ENUM('circle','square','diamond') NOT NULL DEFAULT 'circle',
  `milestone_icon`        VARCHAR(50)  NOT NULL DEFAULT 'gift',
  `popup_enabled`         TINYINT(1)   NOT NULL DEFAULT 0,
  `popup_bg_color`        VARCHAR(20)  NOT NULL DEFAULT '#ffffff',
  `popup_text_color`      VARCHAR(20)  NOT NULL DEFAULT '#202223',
  `popup_border_radius`   VARCHAR(20)  NOT NULL DEFAULT '8px',
  `popup_success_color`   VARCHAR(20)  NOT NULL DEFAULT '#2e7d32',
  `popup_reached_message` VARCHAR(255) NOT NULL DEFAULT 'Congratulations!',
  `popup_styling`         JSON         NULL,
  `created_at`            DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`            DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_template` (`template_id`),
  INDEX `idx_shop` (`shop_domain`),
  CONSTRAINT `fk_tpb_template` FOREIGN KEY (`template_id`) REFERENCES `combo_templates` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `template_milestones` (
  `id`              INT            NOT NULL AUTO_INCREMENT,
  `progressbar_id`  INT            NOT NULL,
  `template_id`     INT            NOT NULL,
  `shop_domain`     VARCHAR(255)   NOT NULL,
  `milestone_value` DECIMAL(12,2)  NOT NULL,
  `label`           VARCHAR(255)   NULL,
  `message`         TEXT           NULL,
  `icon`            VARCHAR(100)   NULL,
  `icon_type`       VARCHAR(20)    NOT NULL DEFAULT 'preset',
  `reward_type`     VARCHAR(50)    NOT NULL DEFAULT 'free_shipping',
  `reward_text`     VARCHAR(255)   NULL,
  `color`           VARCHAR(20)    NOT NULL DEFAULT '#008060',
  `bg_color`        VARCHAR(20)    NOT NULL DEFAULT '#f6f6f7',
  `font_size`       VARCHAR(10)    NOT NULL DEFAULT '12px',
  `is_enabled`      TINYINT(1)     NOT NULL DEFAULT 1,
  `sort_order`      INT            NOT NULL DEFAULT 0,
  `created_at`      DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_progressbar` (`progressbar_id`),
  INDEX `idx_template`    (`template_id`),
  CONSTRAINT `fk_tm_progressbar` FOREIGN KEY (`progressbar_id`) REFERENCES `template_progressbars` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_tm_template`    FOREIGN KEY (`template_id`)    REFERENCES `combo_templates` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `template_ai_blocks` (
  `id`                   INT          NOT NULL AUTO_INCREMENT,
  `template_id`          INT          NOT NULL,
  `shop_domain`          VARCHAR(255) NOT NULL,
  `is_enabled`           TINYINT(1)   NOT NULL DEFAULT 0,
  `heading`              VARCHAR(255) NOT NULL DEFAULT 'You Might Also Like',
  `sub_heading`          VARCHAR(255) NULL,
  `recommendation_count` INT          NOT NULL DEFAULT 4,
  `layout_style`         ENUM('grid','carousel','list') NOT NULL DEFAULT 'grid',
  `background_color`     VARCHAR(20)  NOT NULL DEFAULT '#ffffff',
  `text_color`           VARCHAR(20)  NOT NULL DEFAULT '#202223',
  `price_color`          VARCHAR(20)  NOT NULL DEFAULT '#008060',
  `card_bg_color`        VARCHAR(20)  NOT NULL DEFAULT '#ffffff',
  `card_border_color`    VARCHAR(20)  NOT NULL DEFAULT '#e1e3e5',
  `card_border_radius`   VARCHAR(20)  NOT NULL DEFAULT '8px',
  `card_shadow`          TINYINT(1)   NOT NULL DEFAULT 0,
  `btn_text`             VARCHAR(100) NOT NULL DEFAULT 'Add to Cart',
  `btn_bg_color`         VARCHAR(20)  NOT NULL DEFAULT '#008060',
  `btn_text_color`       VARCHAR(20)  NOT NULL DEFAULT '#ffffff',
  `btn_border_radius`    VARCHAR(20)  NOT NULL DEFAULT '6px',
  `padding`              VARCHAR(20)  NOT NULL DEFAULT '20px',
  `created_at`           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_template` (`template_id`),
  INDEX `idx_shop` (`shop_domain`),
  CONSTRAINT `fk_tai_template` FOREIGN KEY (`template_id`) REFERENCES `combo_templates` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `template_custom_css` (
  `id`            INT          NOT NULL AUTO_INCREMENT,
  `template_id`   INT          NOT NULL,
  `shop_domain`   VARCHAR(255) NOT NULL,
  `css_content`   LONGTEXT     NULL,
  `is_valid`      TINYINT(1)   NOT NULL DEFAULT 1,
  `compiled_hash` VARCHAR(64)  NULL,
  `created_at`    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_template` (`template_id`),
  INDEX `idx_shop` (`shop_domain`),
  CONSTRAINT `fk_tcc_template` FOREIGN KEY (`template_id`) REFERENCES `combo_templates` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `template_revisions` (
  `id`           INT          NOT NULL AUTO_INCREMENT,
  `template_id`  INT          NOT NULL,
  `shop_domain`  VARCHAR(255) NOT NULL,
  `version`      INT          NOT NULL,
  `snapshot`     JSON         NULL,
  `created_by`   VARCHAR(255) NULL,
  `created_at`   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_template_version` (`template_id`, `version`),
  CONSTRAINT `fk_tr_template` FOREIGN KEY (`template_id`) REFERENCES `combo_templates` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── drop orphaned Prisma tables (no route ever queried them) ─────────────────
DROP TABLE IF EXISTS `comboanalytic`;
DROP TABLE IF EXISTS `combotemplate`;
